#!/usr/bin/bash

date=$(date +%Y年%m月%d日)
program_name="testprogram-2"
filename="test_$program_name$date"

/usr/script/radiko/radiko.sh INT 31 "$filename"

id3v2 -a "test" -A "$program_name" -t "$date" "/tmp/radiko_out/$filename.m4a"

#mv "/tmp/radiko_out/$filename.m4a" /srv/share/Music/
